package com.sahar.supportticketback.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

@Getter
@Setter
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name = "AssuranceSante")
public class AssuranceSante {
    private static final long serialVersionUID =1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private  Integer id;

    @Column(name = "carte_identite")
    private String carteIdentite;

    @Column(name = "certificat_medical")
    private String certificatMedical;

    @Column(name = "historique_medical")
    private String historiqueMedical;

    @Column(name = "justificatif_revenus")
    private String justificatifRevenus;
    @OneToOne
    @JoinColumn(name = "client_id")
    private Client client;

    // Constructors, getters, and setters will be generated by Lombok
    public AssuranceSante() {}


}
