package com.sahar.supportticketback.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

@Getter
@Setter
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name = "AssuranceProfessionnelle")
public class AssuranceProfessionnelle {
    private static final long serialVersionUID =1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private  Integer id;
    @Column(name = "extrait_kbis")
    private String extraitKbis;

    @Column(name = "statuts_entreprise")
    private String statutsEntreprise;

    @Column(name = "bilan_comptable")
    private String bilanComptable;

    @Column(name = "justificatif_qualification_professionnelle")
    private String justificatifQualificationProfessionnelle;

    @Column(name = "contrat_travail")
    private String contratTravail;
    @OneToOne
    @JoinColumn(name = "client_id")
    private Client client;

    // Constructors, getters, and setters will be generated by Lombok
    public AssuranceProfessionnelle() {}
}
