package com.sahar.supportticketback.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

@Getter
@Setter
@AllArgsConstructor
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name = "AssuranceVie")
public class AssuranceVie {
    private static final long serialVersionUID =1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private  Integer id;
    @Column(name = "certificat_naissance")
    private String certificatNaissance;

    @Column(name = "examen_medical")
    private String examenMedical;

    @Column(name = "justificatif_revenus")
    private String justificatifRevenus;

    @Column(name = "questionnaire_sante")
    private String questionnaireSante;
    @OneToOne
    @JoinColumn(name = "client_id")
    private Client client;

    // Constructors, getters, and setters will be generated by Lombok
    public AssuranceVie() {}
}
